services:
  - type: web
    name: fashion-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      gunicorn backend.config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
